# Project information
site_name: Crown & Misery Wiki

# TOC and Orders
nav:
  - Home: index.md
  - Lore:
    - lore/index.md
    - Geography and Geopolitics: lore/geography.md
    - Life in Antares: lore/life.md
  - Gameplay:
    - Dice Rolls: gameplay/dice-rolls.md
    - Resources: gameplay/resources.md
    - Spellcasting: gameplay/spellcasting.md
    - Multiclassing: gameplay/multiclassing.md
    - Combat: 
      - Combat Basic: gameplay/combat/basic.md
      - Your Turn: gameplay/combat/your-turn.md
      - Making an Attack: gameplay/combat/making-an-attack.md
      - Movement and Positioning: gameplay/combat/movement.md
      - Damage and Healing : gameplay/combat/damage-healing.md
  - Chartacter Creation:
    - Quickstart: character-creation/quickstart.md
    - Classes: character-creation/classes.md
#   - Races: character-creation/races.md
#   - Feat: character-creation/feat.md
#   - Skills: character-creation/feat.md
    - Ability Score: 
      - character-creation/ability-scores/index.md
      - Strength: character-creation/ability-scores/strength.md
      - Dexterity: character-creation/ability-scores/dexterity.md
      - Constitution: character-creation/ability-scores/constitution.md
      - Intelligence: character-creation/ability-scores/intelligence.md
      - Wisdom: character-creation/ability-scores/wisdom.md
      - Charisma: character-creation/ability-scores/charisma.md
  - Items & Equipment: 
    - Armour: 
      - equipment/armour/index.md
      - Armour Types: equipment/armour/armour-table.md
    - Weapons: 
      - equipment/weapon/index.md
      - Cold Weapons: equipment/weapon/weapon-cold.md
      - Firearms & Explosives: equipment/weapon/weapon-firearm.md
    - Other Equipments: 
      - Tools & Kits: equipment/tools/artisan-tools.md
      - Other Tools: equipment/tools/other-tools.md
    - Consumeables: 
      - Potion: equipment/consumeables/potion.md

# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# CSS
extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

# JavaScript
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - toc.follow
    - content.tooltips
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Reddit Sans
    code: Roboto Mono
  icon: 
    annotation: material/link-circle

# Markdown Extentions
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - tables

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      toc_depth: 4

  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>