# Project information
site_name: Crown & Misery Wiki

# TOC and Orders
nav:
  - Lore:
    - Antares: 
      - lore/antares/index.md
      - Nation-states:
        - London: lore/antares/nation/london.md
        - Myrkheimr: lore/antares/nation/myrkheimr.md
        - Valinor: lore/antares/nation/valinor.md
    - The Warp:
      - lore/warp/index.md
      - Warp Storm: lore/warp/warp-storm.md
      - Entities: lore/warp/warp-entities.md
    - Pantheon: 
      - lore/pantheon/index.md
      - Spires:
        - The Destruction: lore/pantheon/spire-destruction.md
        - The Perseverance: lore/pantheon/spire-perseverance.md
        - The Judgement: lore/pantheon/spire-judgement.md
        - The Harmony: lore/pantheon/spire-harmony.md
  - Gameplay:
    - Dice Rolls: gameplay/dice-rolls.md
    - Resources: gameplay/resources.md
    - Spellcasting: gameplay/spellcasting.md
    - Action Options: gameplay/action-options.md
    - Combat: 
      - gameplay/combat/index.md
      - Making an Attack: gameplay/combat/making-an-attack.md
      - Movement: gameplay/combat/movement.md
      - Damage and Healing : gameplay/combat/damage-healing.md
      - Condition: gameplay/combat/condition.md
    - Homebrew Mechanics:
      - The Silver Standard: gameplay/homebrew/silver-standard.md
      - Death's Door and Resove: gameplay/homebrew/resolve.md
      - Inventory System: gameplay/homebrew/inventory.md
    - Additonal Mechanics:
      - Downtime:
        - gameplay/downtime/index.md
        - Carousing: gameplay/downtime/carousing.md
        - Crafting: gameplay/downtime/crafting.md
        - Crime: gameplay/downtime/crime.md
        - Fishing: gameplay/downtime/fishing.md
        - Gambling: gameplay/downtime/gambling.md
        - Pit Fighting: gameplay/downtime/pit-fighting.md
        - Relaxation: gameplay/downtime/relaxation.md
        - Religious Service: gameplay/downtime/religious-service.md
        - Research: gameplay/downtime/research.md
        - Scribing a Spell Scroll: gameplay/downtime/scribing-scroll.md
        - Selling Magic Item: gameplay/downtime/selling-magic-item.md
        - Training: gameplay/downtime/training.md
        - Work: gameplay/downtime/work.md
    - DM Related: dm/tools.md
  - Chartacter Creation:
    - character-creation/index.md
    - Languages: character-creation/languages.md
    - Multiclassing: character-creation/multiclassing.md
    - Origin:
      - Background: character-creation/background.md
      - Race:
        - character-creation/race/index.md
        - Dragonborn: character-creation/race/dragonborn.md
        - Dwarf: character-creation/race/dwarf.md
        - Elf: character-creation/race/elf.md
        - Gnome: character-creation/race/gnome.md
        - Half Elf: character-creation/race/half-elf.md
        - Half Orc: character-creation/race/half-orc.md
        - Halfling: character-creation/race/halfling.md
        - Human: character-creation/race/human.md
        - Tiefling: character-creation/race/tiefling.md
    - Ability Score: 
      - character-creation/ability-scores/index.md
      - Strength: character-creation/ability-scores/strength.md
      - Dexterity: character-creation/ability-scores/dexterity.md
      - Constitution: character-creation/ability-scores/constitution.md
      - Intelligence: character-creation/ability-scores/intelligence.md
      - Wisdom: character-creation/ability-scores/wisdom.md
      - Charisma: character-creation/ability-scores/charisma.md
    - Feats: 
      - character-creation/feat/index.md
      - Starting Feats: character-creation/feat/feat-starting.md
      - 4th-Level Feats: character-creation/feat/feat-4th-level.md
      - 8th-Level Feats: character-creation/feat/feat-8th-level.md
      - Fighting Style: character-creation/feat/feat-fighting-style.md
      - Racial Feats: character-creation/feat/feat-racial.md
    - Other Options & Features:
      - Metamagic: character-creation/option/metamagic.md
      - Eldritch Invocations: character-creation/option/invocations.md
      - Combat Manoeuvre: character-creation/option/manoeuvre.md
  - Class: 
    - class/index.md
    - Expert Group:
      - Artificer: 
        - class/artificer/index.md
        - Alchemist: class/artificer/alchemist.md
        - Armourer: class/artificer/armourer.md
        - Artilerist: class/artificer/artilerist.md
        - Battlesmith: class/artificer/battlesmith.md
      - Bard: 
        - class/bard/index.md
        - Dance: class/bard/dance.md
        - Glamour: class/bard/glamour.md
        - Lore: class/bard/lore.md
        - Valour: class/bard/valour.md
      - Ranger: 
        - class/ranger/index.md
        - Beast Master: class/ranger/beast-master.md
        - Fey Wanderer: class/ranger/fey-wanderer.md
        - Gloom Stalker: class/ranger/gloom-stalker.md
        - Hunter: class/ranger/hunter.md
      - Rogue: 
        - class/rogue/index.md
        - Arcane Trickster: class/rogue/arcane-trickster.md
        - Assassin: class/rogue/assassin.md
        - Soulknife: class/rogue/soulknife.md
        - Swashbuckler: class/rogue/swashbuckler.md
        - Thief: class/rogue/thief.md
    - Mage Group:
      - Sorcerer:
        - class/sorcerer/index.md
        - Abberant Mind: class/sorcerer/aberrant.md
        - Clockwork Soul: class/sorcerer/clockwork.md
        - Draconic Bloodline: class/sorcerer/draconic.md
        - Stone Sorcery: class/sorcerer/stone.md
        - Wild Magic: class/sorcerer/wild.md
      - Warlock:
        - class/warlock/index.md
        - Archfey: class/warlock/archfey.md
        - Celestial: class/warlock/celestial.md
        - Fiend: class/warlock/fiend.md
        - Great Old One: class/warlock/great-old-one.md
      - Wizard:
        - class/wizard/index.md
        - Abjurer: class/wizard/abjurer.md
        - Diviner: class/wizard/diviner.md
        - Evoker: class/wizard/evoker.md
        - Illusionist: class/wizard/illusionist.md
    - Priest Group:
      - Cleric:
        - class/cleric/index.md
        - Life: class/cleric/life.md
        - Light: class/cleric/light.md
        - Trickery: class/cleric/trickery.md
        - War: class/cleric/war.md
      - Druid:
        - class/druid/index.md
        - Land: class/druid/land.md
        - Moon: class/druid/moon.md
        - Sea: class/druid/sea.md
        - Stars: class/druid/star.md
      - Paladin:
        - class/paladin/index.md
        - Devotion: class/paladin/devotion.md
        - Glory: class/paladin/glory.md
        - The Ancient: class/paladin/ancient.md
        - Vengeance: class/paladin/vengeance.md
    - Warrior Group:
      - Barbarian:  
        - class/barbarian/index.md
        - Berserker: class/barbarian/berserker.md
        - Wild Heart: class/barbarian/wild-heart.md
        - World Tree: class/barbarian/world-tree.md
        - Zealot: class/barbarian/zealot.md
      - Fighter:
        - class/fighter/index.md
        - Battlemaster: class/fighter/battlemaster.md
        - Brawler: class/fighter/brawler.md
        - Champion: class/fighter/champion.md
        - Eldritch Knight: class/fighter/eldritch-knight.md
        - Psi Warrior: class/fighter/psi-warrior.md
      - Monk:
        - class/monk/index.md
        - Elements: class/monk/element.md
        - Hand: class/monk/hand.md
        - Shadow: class/monk/shadow.md
  - Items & Equipment: 
    - Armour: 
      - equipment/armour/index.md
      - Armour Types: equipment/armour/armour-table.md
    - Weapons: 
      - equipment/weapon/index.md
      - Cold Weapons: equipment/weapon/weapon-cold.md
      - Firearms: equipment/weapon/weapon-firearm.md
    - Equipments: 
      - Adventuring Gear: equipment/tools/adventuring-gear.md
      - Tools & Kits: equipment/tools/artisan-tools.md
      - Other Tools: equipment/tools/other-tools.md
      - Backpack: equipment/tools/backpack.md
    - Consumeables: 
      - Potion: equipment/consumeables/potion.md
      - Spell Scroll: equipment/consumeables/spell-scroll.md
      - Grenade: equipment/consumeables/grenade.md
  - Spells:
    - Cantrip: spells/cantrip.md
    - Level 1 Spell: spells/1st-level.md
    - Level 2 Spell: spells/2nd-level.md
    - Level 3 Spell: spells/3rd-level.md
    - Level 4 Spell: spells/4th-level.md
    - Level 5 Spell: spells/5th-level.md
    - Level 6 Spell: spells/6th-level.md
    - Level 7 Spell: spells/7th-level.md
    - Level 8 Spell: spells/8th-level.md
    - Level 9 Spell: spells/9th-level.md
  - Current Campaign:
    - Player's Gimmick:
      - John K. Godsmith: campaign/player-chr/john-godsmith.md
      - Ydastriel Khaine: campaign/player-chr/ydastriel-khaine.md
      - Eris Decrat: campaign/player-chr/eris-dekrat.md
    - Changelog: campaign/changelog.md
# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# CSS
extra_css:
  - css/extra.css
  - css/admonition.css

# - https://unpkg.com/katex@0/dist/katex.min.css

# JavaScript
# 3xtra_javascript:
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - content.tooltips
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  language: en
  palette:
    scheme: slate
    primary: black
    accent: teal
  font:
    code: Inconsolata
    text: Roboto Slab
  icon: 
    logo: fontawesome/solid/dice-d20
    annotation: material/timeline-question
  favicon: assets/icon.jpg

# Markdown Extentions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
#      permalink: true
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>