# Project information
site_name: Crown & Misery Wiki

# Author
site_author: Eschatologue
site_url: https://eschatologue.github.io/CM_wiki/
site_description: >-
 A Wiki for Personal D&D Campaign. 

# CSS
extra_css:
  - assets/css/extra.css

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - content.tooltips
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  language: en
  palette:
    scheme: slate ## DON'T CHANGE THIS
    primary: indigo
    accent: indigo
  font:
    code: JetBrains Mono
    text: Source Sans 3 ## This is good enough, don't change it again.
  favicon: assets/icon.jpg
  static_templates:
    - 404.html
  icon: 
    logo: fontawesome/solid/dice-d20
    annotation: material/star-four-points-circle
  
## Additional Configuration
extra:
  status:
    homebrew: Homebrew Material
    adapted: Adapted to PHB'24
    draft: Draft

# Markdown Extentions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>

watch:
  - includes
  - overrides

# Nav
nav:
  - Playing the Game:
    - PHB'24 Mechanics: 
      - Dice: gameplay/phb/dice.md
      - The Six Abilities: 
        - gameplay/phb/abilities/index.md
        - Strength: gameplay/phb/abilities/strength.md
        - Dexterity: gameplay/phb/abilities/dexterity.md
        - Constitution: gameplay/phb/abilities/constitution.md
        - Intelligence: gameplay/phb/abilities/intelligence.md
        - Wisdom: gameplay/phb/abilities/wisdom.md
        - Charisma: gameplay/phb/abilities/charisma.md
      - D20 Test: gameplay/phb/d20-test.md
      - Proficiency: gameplay/phb/proficiency.md
      - Actions: gameplay/phb/action.md
      - Exploration: gameplay/phb/exploration.md
      - Combat: gameplay/phb/combat.md
      - Damage & Healing: gameplay/phb/damage-and-healing.md
      - Condition: gameplay/phb/condition.md
    - Additional Mechanics:
      - The Silver Standard: gameplay/homebrew/silver-standard.md
      - Inventory System: gameplay/homebrew/inventory.md
      - Fishing: 
        - gameplay/homebrew/fishing/index.md
        - Appendix: gameplay/homebrew/fishing/appendix.md
      - Downtime:
        - gameplay/downtime/index.md
        - Carousing: gameplay/downtime/carousing.md
        - Crime: gameplay/downtime/crime.md
        - Gambling: gameplay/downtime/gambling.md
        - Pit Fighting: gameplay/downtime/pit-fighting.md
        - Relaxation: gameplay/downtime/relaxation.md
        - Religious Service: gameplay/downtime/religious-service.md
        - Research: gameplay/downtime/research.md
        - Selling Magic Item: gameplay/downtime/selling-magic-item.md
        - Training: gameplay/downtime/training.md
        - Work: gameplay/downtime/work.md
    - Glossaries: 
      - Rule Glossary: glossary.md
      - Quick Reference: quickref.md
#    - Icconography : iconography.md
  - Character Creation:
    - Create Your Character: chr-creation/create-your-character.md
    - Starting at Higher Level: chr-creation/starting-at-higher-level.md
    - Multiclassing: chr-creation/multiclassing.md
    - Trinket: chr-creation/trinket.md
    - Origin:
      - Background: chr-creation/origin/background.md
        # - Common Background: chr-creation/origin/background/common-background.md
        # - Special Background: chr-creation/origin/background/special-background.md
      - Species:
        - chr-creation/origin/species/index.md
        - Aasimar: chr-creation/origin/species/aasimar.md
        - Dragonborn: chr-creation/origin/species/dragonborn.md
        - Dwarf: chr-creation/origin/species/dwarf.md
        - Elf: chr-creation/origin/species/elf.md
        - Gnome: chr-creation/origin/species/gnome.md
        - Goliath: chr-creation/origin/species/goliath.md
        - Halfling: chr-creation/origin/species/halfling.md
        - Half Elf: chr-creation/origin/species/half-elf.md       
        - Human: chr-creation/origin/species/human.md
        - Londoner: chr-creation/origin/species/londoner.md
        - Orc: chr-creation/origin/species/orc.md
        - Tiefling: chr-creation/origin/species/tiefling.md
      - Affiliation: chr-creation/origin/affiliation.md
  - Feats & Class Options:
    - Feats: 
      - option/feat/index.md
      - Origin Feats: 
        - option/feat/feat-origin/index.md
        - PHB'24: option/feat/feat-origin/phb24.md
        - Homebrew: option/feat/feat-origin/hb.md
      - General Feats: 
        - option/feat/feat-general/index.md
        - PHB'24: option/feat/feat-general/phb24.md
        - Homebrew: option/feat/feat-general/hb.md
      - Advanced Feats: option/feat/feat-advanced.md
      - Epic Boon: option/feat/feat-boon.md
      - Fighting Style: 
        - option/feat/feat-fighting-style/index.md
        - PHB'24: option/feat/feat-fighting-style/phb24.md
        - Homebrew: option/feat/feat-fighting-style/hb.md
    - Class Options:
      - Infusion: 
        - option/class-options/artificer-infusion/index.md
        - TCE: option/class-options/artificer-infusion/tce.md
        - Homebrew: option/class-options/artificer-infusion/hb.md
      - Metamagic: 
        - option/class-options/sorcerer-metamagic/index.md
        - PHB'24: option/class-options/sorcerer-metamagic/phb24.md
        - Homebrew: option/class-options/sorcerer-metamagic/hb.md
      - Eldritch Invocations: 
        - option/class-options/warlock-invocations/index.md
        - PHB'24: option/class-options/warlock-invocations/phb24.md
        - Homebrew: option/class-options/warlock-invocations/hb.md
      - Combat Manoeuvre: 
        - option/class-options/fighter-manoeuvre/index.md
        - PHB'24: option/class-options/fighter-manoeuvre/phb24.md
        - Homebrew: option/class-options/fighter-manoeuvre/hb.md
      - Ranger's Aptitude: option/class-options/ranger-aptitude.md
  - Equipment: 
      - Crafting Equipment: equipment/crafting.md
      - Magic Items: equipment/magic-item.md
      - Services: equipment/services.md
      - Armaments:
        - Armour: equipment/armour.md 
        - Weapons: 
          - equipment/weapon/index.md
          - Mastery properties: equipment/weapon/mastery.md
          - Cold Weapons: equipment/weapon/weapon-cold.md
          - Firearms: equipment/weapon/weapon-firearm.md 
      - Tools: 
        - equipment/tools/index.md
        - Artisan Tools: equipment/tools/artisan-tools.md
        - Other Tools: equipment/tools/other-tools.md
      - Adventuring Gear: 
          - Equipment Packs: equipment/adventuring-gear/equipment-packs.md
          - Containers Items: equipment/adventuring-gear/containers.md
          - Spellcasting Focuses: equipment/adventuring-gear/spellcasting-focus.md
          - Items: equipment/adventuring-gear/item.md
          - Homebrew Items: equipment/adventuring-gear/item-hb.md
      - Other: 
        - Grenade: equipment/consumeables/grenade.md
        - Potion: equipment/consumeables/potion.md
        - Spell Scroll: equipment/consumeables/spell-scroll.md
  - Class: 
    - class/index.md
    - Expert Group:
      - Artificer: 
        - class/artificer/index.md
        - Alchemist: class/artificer/alchemist.md
        - Armourer: class/artificer/armourer.md
        - Artilerist: class/artificer/artilerist.md
        - Battlesmith: class/artificer/battlesmith.md
        - Forgewright: class/artificer/forgewright.md
        - Gunslinger: class/artificer/gunslinger.md
      - Bard: 
        - class/bard/index.md
        - Dance: class/bard/dance.md
        - Glamour: class/bard/glamour.md
        - Lore: class/bard/lore.md
        - Valour: class/bard/valour.md
        - Eloquence: class/bard/eloquence.md
        - Spirits: class/bard/spirits.md
        - Swords: class/bard/swords.md
        - Whispers: class/bard/whispers.md
        - Debate: class/bard/debate.md
        - Skald: class/bard/skald.md
        - Tragedy: class/bard/tragedy.md
      - Ranger: 
        - class/ranger/index.md
        - Beast Master: class/ranger/beast-master.md
        - Fey Wanderer: class/ranger/fey-wanderer.md
        - Gloom Stalker: class/ranger/gloom-stalker.md
        - Hunter: class/ranger/hunter.md
        - Monster Slayer: class/ranger/monster-slayer.md
        - Broodweaver: class/ranger/broodweaver.md
        - Grove Keeper: class/ranger/grove-keeper.md
        - Spellbreaker: class/ranger/spellbreaker.md
      - Rogue: 
        - class/rogue/index.md
        - Arcane Trickster: class/rogue/arcane-trickster.md
        - Assassin: class/rogue/assassin.md
        - Soulknife: class/rogue/soulknife.md
        - Thief: class/rogue/thief.md
        - Scout: class/rogue/scout.md
        - Swashbuckler: class/rogue/swashbuckler.md
        - Justiciar: class/rogue/justiciar.md
        - Saboteur: class/rogue/saboteur.md
    - Mage Group:
      - Sorcerer:
        - class/sorcerer/index.md
        - Abberant Mind: class/sorcerer/aberrant.md
        - Clockwork Soul: class/sorcerer/clockwork.md
        - Draconic Sorcery: class/sorcerer/draconic.md
        - Spellfire: class/sorcerer/spellfire.md
        - Wild Magic: class/sorcerer/wild.md
        - Divine Soul: class/sorcerer/divine.md
        - Lunar Sorcery: class/sorcerer/lunar.md
        - Stone Sorcery: class/sorcerer/stone.md
        - Storm Sorcery: class/sorcerer/storm.md
        - Arcane Soul: class/sorcerer/arcane.md
        - Voidwielder: class/sorcerer/voidwielder.md
      - Warlock:
        - class/warlock/index.md
        - Archfey: class/warlock/archfey.md
        - Celestial: class/warlock/celestial.md
        - Fiend: class/warlock/fiend.md
        - Great Old One: class/warlock/great-old-one.md
        - Hexblade: class/warlock/hexblade.md
        - Archmage: class/warlock/archmage.md
        - Broodlord: class/warlock/broodlord.md
      - Wizard:
        - class/wizard/index.md
        - Abjurer: class/wizard/abjurer.md
        - Bladesinger: class/wizard/bladesinger.md
        - Diviner: class/wizard/diviner.md
        - Evoker: class/wizard/evoker.md
        - Illusionist: class/wizard/illusionist.md
        - Chronurgist: class/wizard/chronurgist.md
        - War Mage: class/wizard/war-mage.md
        - Hedge Mage: class/wizard/hedge-mage.md
        - Technomage: class/wizard/technomage.md
    - Priest Group:
      - Cleric:
        - class/cleric/index.md
        - Life: class/cleric/life.md
        - Light: class/cleric/light.md
        - Trickery: class/cleric/trickery.md
        - War: class/cleric/war.md
        - Arcana: class/cleric/arcana.md
        - Forge: class/cleric/forge.md
        - Order: class/cleric/order.md
        - Tempest: class/cleric/tempest.md
        - Twilight: class/cleric/twilight.md
        - Destruction: class/cleric/destruction.md
      - Druid:
        - class/druid/index.md
        - Land: class/druid/land.md
        - Moon: class/druid/moon.md
        - Sea: class/druid/sea.md
        - Stars: class/druid/star.md
        - Forged: class/druid/forged.md
      - Paladin:
        - class/paladin/index.md
        - Devotion: class/paladin/devotion.md
        - Glory: class/paladin/glory.md
        - The Ancient: class/paladin/ancient.md
        - Vengeance: class/paladin/vengeance.md
        - Conquest: class/paladin/conquest.md
        - The Crown: class/paladin/crown.md
        - Watchers: class/paladin/watchers.md
        - Oathbreaker: class/paladin/oathbreaker.md
        - Bastion: class/paladin/bastion.md
        - Oathless: class/paladin/oathless.md
        - The Blade: class/paladin/blade.md
    - Warrior Group:
      - Barbarian:  
        - class/barbarian/index.md
        - Berserker: class/barbarian/berserker.md
        - Wild Heart: class/barbarian/wild-heart.md
        - World Tree: class/barbarian/world-tree.md
        - Zealot: class/barbarian/zealot.md
        - Ancestral Guardian: class/barbarian/ancestral-guardian.md
        - Battlerager: class/barbarian/battlerager.md
        - Giant: class/barbarian/giant.md
        - Storm Herald: class/barbarian/storm-herald.md
        - Ruffian: class/barbarian/ruffian.md 
        - Tranquillity: class/barbarian/tranquillity.md    
      - Fighter:
        - class/fighter/index.md
        - Battlemaster: class/fighter/battlemaster.md
        - Champion: class/fighter/champion.md
        - Eldritch Knight: class/fighter/eldritch-knight.md
        - Psi Warrior: class/fighter/psi-warrior.md
        - Echo Knight: class/fighter/echo-knight.md
        - Runecarver: class/fighter/runecarver.md
        - Samurai: class/fighter/samurai.md
        - Witchblade: class/fighter/witchblade.md
      - Monk:
        - class/monk/index.md
        - Mercy: class/monk/mercy.md
        - Shadow: class/monk/shadow.md
        - Hand: class/monk/hand.md
        - Elements: class/monk/element.md
        - Ascendant Dragon: class/monk/dragon.md
        - Astral Self: class/monk/astral.md
        - Drunken Warrior: class/monk/drunken.md
        - Sun Soul: class/monk/sun-soul.md
        - Wuxia: class/monk/wuxia.md
      - Magus:
        - class/magus/index.md
        - Arcanist: class/magus/arcanist.md
        - Blade Dancer: class/magus/blade-dancer.md
        - Traveler: class/magus/traveler.md
        - Spellbreaker: class/magus/spellbreaker.md
        - Warder: class/magus/warder.md
  - Spells:
    - Gaining Spells: spells/gaining-spells.md
    - Casting Spells: spells/casting-spells.md
    - Class Specific Spells:
      - Half-Caster:
        - Paladin: spells/class-specific/paladin.md
        - Ranger: spells/class-specific/ranger.md
      - Two-Third-Caster:
        - Artificer: spells/class-specific/artificer.md
        - Magus: spells/class-specific/magus.md
      - Full-Caster:
        - Bard: spells/class-specific/bard.md
        - Cleric: spells/class-specific/cleric.md
        - Druid: spells/class-specific/druid.md
        - Sorcerer: spells/class-specific/sorcerer.md
        - Warlock: spells/class-specific/warlock.md
        - Wizard: spells/class-specific/wizard.md
    - Spells Description:
      - Core Rulebook: 
        - Cantrip: spells/description/core/cantrip.md
        - Level 1: spells/description/core/level-1.md
        - Level 2: spells/description/core/level-2.md
        - Level 3: spells/description/core/level-3.md
        - Level 4: spells/description/core/level-4.md
        - Level 5: spells/description/core/level-5.md
        - Level 6: spells/description/core/level-6.md
        - Level 7: spells/description/core/level-7.md
        - Level 8: spells/description/core/level-8.md
        - Level 9: spells/description/core/level-9.md
      - Additional: 
        - Dunamancy: spells/description/additional/dunamancy.md
        - Homebrew: spells/description/additional/homebrew.md
  - Campaign:
    - Player's Gimmick:
      - John K. Godsmith: campaign/player-chr/john-godsmith.md
      - Ydastriel Khaine: campaign/player-chr/ydastriel-khaine.md
      - Eris Decrat: campaign/player-chr/eris-dekrat.md
  - Lore:
    - Antares: 
      - Continent: lore/antares/continent.md
      - Nation:
        - Albion: lore/antares/nation/london.md
        - Gallia: lore/antares/nation/gallia.md
        - Karakorum: lore/antares/nation/karakorum.md
        - Lothringen: lore/antares/nation/lothringen.md
        - Myrkheim: lore/antares/nation/myrkheim.md
        - Soterrano: lore/antares/nation/soterrano.md
        - Tartessia: lore/antares/nation/tartessia.md
        - Valinor: lore/antares/nation/valinor.md
      - Life: lore/antares/life.md
      - Race: 
        - Aasimar: lore/antares/race/aasimar.md
        - Dwarf: lore/antares/race/dwarf.md
        - Elf: lore/antares/race/elf.md
        - Londoner: lore/antares/race/londoner.md
    - The Warp:
      - lore/warp/index.md
      - Entities: lore/warp/warp-entities.md
      - Warp Storm: lore/warp/warp-storm.md
      - Voidite: lore/warp/voidite.md
    - Pantheon: 
      - lore/pantheon/index.md
      - Spires:
        - The Destruction: lore/pantheon/spire-destruction.md
        - The Enlightenment: lore/pantheon/spire-enlightenment.md
        - The Equillibrium: lore/pantheon/spire-equillibrium.md
        - The Harmony: lore/pantheon/spire-harmony.md
        - The Judgement: lore/pantheon/spire-judgement.md
        - The Perseverance: lore/pantheon/spire-perseverance.md
    - Lore Glossary: lore/glossary.md