# Project information
site_name: Crown & Misery Wiki

# TOC and Orders
nav:
  - Home: index.md
  - Lore:
    - Antares: antares/antares.md
    - Geography and Geopolitics: antares/geography.md
    - Life in Antares: antares/life.md
  - Gameplay:
    - Dice Rolls: gameplay/dice-rolls.md
    - Resources: gameplay/resources.md
    - Combat: gameplay/combat.md
    - Spellcasting: gameplay/spellcasting.md
    - Multiclassing: gameplay/multiclassing.md
  - Chartacter Creation:
    - Quickstart: character-creation/quickstart.md
    - Ability Score: 
      - character-creation/ability-score.md
      - Strength: character-creation/as-01.strength.md
      - Dexterity: character-creation/as-02.dexterity.md
      - Constitution: character-creation/as-03.constitution.md
      - Intelligence: character-creation/as-04.intelligence.md
      - Wisdom: character-creation/as-05.wisdom.md
      - Charisma: character-creation/as-06.charisma.md
#    - Races: character-creation/races.md
    - Classes: character-creation/classes.md
#    - Feat: character-creation/feat.md
#    - Skills: character-creation/feat.md
  - Items & Equipment: 
    - Armour: equipment/armour.md
    - Weapons: equipment/weapon.md
    - Firearms: equipment/firearm.md
    - Tools: equipment/tools.md
    - Potion & Consumeables: equipment/potion.md
  - Quick Reference:
#    - Action Type: quickref/actiontypes.md
    - Condition and Disease: quickref/condition.md
    - Armour Class: quickref/ac.md
#    - Damage Types: quickref/damagetypes.md

# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# CSS
extra_css:
  - css/extra.css

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:

    # Nav
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.path
  
    - content.tooltips

    # toc.integrate
    - toc.follow

    - admonition
    - pymdownx.details
    - pymdownx.superfences

  language: en

# Palette
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# Font
  font:
    text: Reddit Sans
    code: Roboto Mono
  # logo: PyTorch_logo_icon.svg

# Markdown Extentions
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - tables

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true

  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>