# Project information
site_name: CROWN AND MISERY WIKI

# TOC and Orders
nav:
  - Home: main.md
  - Lore:
    - Antares: antares/antares.md
    - Geography and Geopolitics: antares/geography.md
    - Life: antares/life.md
  - Gameplay:
    # Character Creations: 
    - Playing the Game: gameplay/playing-the-game.md
    - Combat: gameplay/combat.md
    - Spellcasting: gameplay/spellcasting.md

# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# Configuration
theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking

    # toc.integrate
    - toc.follow

  language: en

# Palette
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# Font
  font:
    text: Roboto
    code: Roboto Mono
  # logo: PyTorch_logo_icon.svg

# Markdown Extentions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>