# Project information
site_name: Crown & Misery Wiki

# TOC and Orders
nav:
  - Lore:
    - Antares: 
      - lore/antares/index.md
      - Nation-states:
        - London: lore/antares/nation/london.md
        - Myrkheimr: lore/antares/nation/myrkheimr.md
    - The Warp:
      - lore/warp/index.md
      - Warp Storm: lore/warp/warp-storm.md
      - Warp Entities: lore/warp/warp-entities.md
    - Pantheon: lore/pantheon.md
    - The Celestial Language: lore/celestial.md
  - Gameplay:
    - Dice Rolls: gameplay/dice-rolls.md
    - Resources: gameplay/resources.md
    - Spellcasting: gameplay/spellcasting.md
    - Multiclassing: gameplay/multiclassing.md
    - Combat: 
      - gameplay/combat/index.md
      - Making an Attack: gameplay/combat/making-an-attack.md
      - Movement: gameplay/combat/movement.md
      - Damage and Healing : gameplay/combat/damage-healing.md
      - Condition: gameplay/combat/condition.md
    - Homebrew Mechanics:
      - Affiliation: gameplay/homebrew/affiliation.md
      - Death's Door and Resove: gameplay/homebrew/resolve.md
      - Inventory System: gameplay/homebrew/inventory.md
      - Fishing and Angling: gameplay/homebrew/fishing.md
    - DM Related: dm/tools.md
  - Chartacter Creation:
    - Quickstart: character-creation/quickstart.md
    - Classes: character-creation/classes.md
    - Race: character-creation/race/race.md
    - Languages: character-creation/languages.md
    - Ability Score: 
      - character-creation/ability-scores/index.md
      - Strength: character-creation/ability-scores/strength.md
      - Dexterity: character-creation/ability-scores/dexterity.md
      - Constitution: character-creation/ability-scores/constitution.md
      - Intelligence: character-creation/ability-scores/intelligence.md
      - Wisdom: character-creation/ability-scores/wisdom.md
      - Charisma: character-creation/ability-scores/charisma.md
    - Feats: 
      - character-creation/feat/index.md
      - Starting Feats: character-creation/feat/feat-starting.md
      - 4th-Level Feats: character-creation/feat/feat-4th-level.md
      - 8th-Level Feats: character-creation/feat/feat-8th-level.md
      - Fighting Style: character-creation/feat/feat-fighting-style.md
    - Other Options & Features:
      - Metamagic: character-creation/option/metamagic.md
      - Eldritch Invocations: character-creation/option/invocations.md
  - Items & Equipment: 
    - Armour: 
      - equipment/armour/index.md
      - Armour Types: equipment/armour/armour-table.md
    - Weapons: 
      - equipment/weapon/index.md
      - Cold Weapons: equipment/weapon/weapon-cold.md
      - Firearms & Explosives: equipment/weapon/weapon-firearm.md
    - Equipments: 
      - Adventuring Gear: equipment/tools/adventuring-gear.md
      - Tools & Kits: equipment/tools/artisan-tools.md
      - Other Tools: equipment/tools/other-tools.md
      - Backpack: equipment/tools/backpack.md
    - Consumeables: 
      - Potion: equipment/consumeables/potion.md
  - Spells:
    - Cantrip: spells/cantrip.md
    - 1st-level Spell: spells/1st-level.md
    - 2nd-level Spell: spells/2nd-level.md
    - 3rd-level Spell: spells/3rd-level.md
    - 4th-level Spell: spells/4th-level.md
    - 5th-level Spell: spells/5th-level.md
    - 6th-level Spell: spells/6th-level.md
    - 7th-level Spell: spells/7th-level.md
    - 8th-level Spell: spells/8th-level.md
    - 9th-level Spell: spells/9th-level.md
  - Current Campaign:
    - Player's Gimmick:
      - John K. Godsmith: campaign/player-chr/john-godsmith.md
      - Ydastriel Khaine: campaign/player-chr/ydastriel-khaine.md
      - Eris Decrat: campaign/player-chr/eris-dekrat.md
    - Changelog: campaign/changelog.md
# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# CSS
extra_css:
  - css/extra.css
  - css/admonition.css

# - https://unpkg.com/katex@0/dist/katex.min.css

# JavaScript
# 3xtra_javascript:
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - content.tooltips
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  language: en
  palette:
    scheme: slate
    primary: black
    accent: teal
  font:
    code: Roboto Mono
    text: Roboto Slab
  icon: 
    logo: fontawesome/solid/dice-d20
    annotation: material/timeline-question
  favicon: assets/icon.jpg

# Markdown Extentions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 4
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>