# Project information
site_name: CROWN AND MISERY WIKI

# TOC and Orders
nav:
  - Home: index.md
  - Lore:
    - Antares: antares/antares.md
    - Geography and Geopolitics: antares/geography.md
    - Life in Antares: antares/life.md
  - Gameplay & Basics:
    - Playing the Game: gameplay/playing-the-game.md
    - Combat: gameplay/combat.md
    - Spellcasting: gameplay/spellcasting.md
    - Multiclassing: gameplay/multiclassing.md
  - Chartacter Creation:
    - Quickstart: character-creation/quickstart.md
#    - Races: character-creation/races.md
    - Classes: character-creation/classes.md
#    - Feat: character-creation/feat.md
#    - Skills: character-creation/feat.md


# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# CSS
extra_css:
  - css/extra.css

# Configuration
theme:
  name: material
  features:
    # Nav
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
  
    - content.tooltips

    # toc.integrate
    - toc.follow

    - admonition
    - pymdownx.details
    - pymdownx.superfences

  language: en

# Palette
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# Font
  font:
    text: Roboto
    code: Roboto Mono
  # logo: PyTorch_logo_icon.svg

# Markdown Extentions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - tables

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>