# Project information
site_name: Crown & Misery Wiki

# TOC and Orders
nav:
  - Lore:
    - Antares: 
      - lore/antares/index.md
      - Nation-states:
        - London: lore/antares/nation/london.md
        - Myrkheim: lore/antares/nation/myrkheimr.md
        - Valinor: lore/antares/nation/valinor.md
    - The Warp:
      - lore/warp/index.md
      - Warp Storm: lore/warp/warp-storm.md
      - Entities: lore/warp/warp-entities.md
    - Pantheon: 
      - lore/pantheon/index.md
      - Spires:
        - The Destruction: lore/pantheon/spire-destruction.md
        - The Perseverance: lore/pantheon/spire-perseverance.md
        - The Judgement: lore/pantheon/spire-judgement.md
        - The Harmony: lore/pantheon/spire-harmony.md
    - Notable Events:
      - The Great Split: lore/event/great-split.md
  - Playing the Game:
    - 2024 Player's Handbook Mechanics: 
      - Dice: gameplay/phb/dice.md
      - The Six Abilities: gameplay/phb/abilities.md
      - D20 Test: gameplay/phb/d20-test.md
      - Proficiency: gameplay/phb/proficiency.md
      - Actions: 
        - gameplay/phb/actions/index.md
        - Options: gameplay/phb/actions/options.md
      - Exploration: gameplay/phb/exploration.md
      - Combat: gameplay/phb/combat.md
      - Damage & Healing: gameplay/phb/damage-and-healing.md
      - Condition: gameplay/phb/condition.md
    - Additional Mechanics:
      - The Silver Standard: gameplay/homebrew/silver-standard.md
      - Inventory System: gameplay/homebrew/inventory.md
      - Downtime:
        - gameplay/downtime/index.md
        - Carousing: gameplay/downtime/carousing.md
        - Crafting: gameplay/downtime/crafting.md
        - Crime: gameplay/downtime/crime.md
        - Fishing: gameplay/downtime/fishing.md
        - Gambling: gameplay/downtime/gambling.md
        - Pit Fighting: gameplay/downtime/pit-fighting.md
        - Relaxation: gameplay/downtime/relaxation.md
        - Religious Service: gameplay/downtime/religious-service.md
        - Research: gameplay/downtime/research.md
        - Scribing a Spell Scroll: gameplay/downtime/scribing-scroll.md
        - Selling Magic Item: gameplay/downtime/selling-magic-item.md
        - Training: gameplay/downtime/training.md
        - Work: gameplay/downtime/work.md
  - Chartacter Creation:
    - Create Your Character: character-creation/create-your-character.md
    - Starting at Higher Level: character-creation/starting-at-higher-level.md
    - Multiclassing: character-creation/multiclassing.md
    - Trinket: character-creation/trinket.md
    - Origin:
      - Background: 
        - character-creation/origin/background/index.md
        - Common Background: character-creation/origin/background/common-background.md
        - Special Background: character-creation/origin/background/special-background.md
      - Species:
        - character-creation/origin/species/index.md
        - Aasimar: character-creation/origin/species/aasimar.md
        - Dragonborn: character-creation/origin/species/dragonborn.md
        - Dwarf: character-creation/origin/species/dwarf.md
        - Elf: character-creation/origin/species/elf.md
        - Gnome: character-creation/origin/species/gnome.md
        - Goliath: character-creation/origin/species/goliath.md
        - Halfling: character-creation/origin/species/halfling.md
        - Half Elf: character-creation/origin/species/half-elf.md       
        - Human: character-creation/origin/species/human.md
        - Londoner: character-creation/origin/species/londoner.md
        - Orc: character-creation/origin/species/orc.md
        - Tiefling: character-creation/origin/species/tiefling.md
    - Ability Score: 
      - character-creation/ability-scores/index.md
      - Strength: character-creation/ability-scores/strength.md
      - Dexterity: character-creation/ability-scores/dexterity.md
      - Constitution: character-creation/ability-scores/constitution.md
      - Intelligence: character-creation/ability-scores/intelligence.md
      - Wisdom: character-creation/ability-scores/wisdom.md
      - Charisma: character-creation/ability-scores/charisma.md
    - Feats: 
      - character-creation/feat/index.md
      - Origin Feats: character-creation/feat/feat-origin.md
      - General Feats: character-creation/feat/feat-general.md
      - Advanced Feats: character-creation/feat/feat-advanced.md
      - Epic Boon: character-creation/feat/feat-boon.md
      - Fighting Style: character-creation/feat/feat-fighting-style.md
    - Other Options & Features:
      - Artificer's Infusion: character-creation/option/artificer-infusion.md
      - Metamagic: character-creation/option/metamagic.md
      - Eldritch Invocations: character-creation/option/invocations.md
      - Combat Manoeuvre: character-creation/option/manoeuvre.md
  - Equipment: 
      - Weapons: 
        - equipment/weapon/index.md
        - Cold Weapons: equipment/weapon/weapon-cold.md
        - Firearms: equipment/weapon/weapon-firearm.md
      - Armour: equipment/armour.md 
      - Tools: 
        - equipment/tools/index.md
        - Artisan Tools: equipment/tools/artisan-tools.md
        - Other Tools: equipment/tools/other-tools.md
      - Adventuring Gear: 
          - Equipment Packs: equipment/adventuring-gear/equipment-packs.md
          - Spellcasting Focuses: equipment/adventuring-gear/spellcasting-focus.md
          - Items: equipment/adventuring-gear/item.md
      - Services: equipment/services.md
      - Magic Items: equipment/magic-item.md
      - Consumeables: 
        - Potion: equipment/consumeables/potion.md
        - Spell Scroll: equipment/consumeables/spell-scroll.md
        - Grenade: equipment/consumeables/grenade.md
  - Class: 
    - class/index.md
    - Expert Group:
      - Artificer: 
        - class/artificer/index.md
        - Alchemist: class/artificer/alchemist.md
        - Armourer: class/artificer/armourer.md
        - Artilerist: class/artificer/artilerist.md
        - Battlesmith: class/artificer/battlesmith.md
        - Gunslinger (HB): class/artificer/gunslinger.md
      - Bard: 
        - class/bard/index.md
        - Dance: class/bard/dance.md
        - Glamour: class/bard/glamour.md
        - Lore: class/bard/lore.md
        - Valour: class/bard/valour.md
        - Swords (HB): class/bard/swords.md
      - Ranger: 
        - class/ranger/index.md
        - Beast Master: class/ranger/beast-master.md
        - Fey Wanderer: class/ranger/fey-wanderer.md
        - Gloom Stalker: class/ranger/gloom-stalker.md
        - Hunter: class/ranger/hunter.md
        - Spellbreaker (HB): class/ranger/spellbreaker.md
      - Rogue: 
        - class/rogue/index.md
        - Arcane Trickster: class/rogue/arcane-trickster.md
        - Assassin: class/rogue/assassin.md
        - Soulknife: class/rogue/soulknife.md
        - Thief: class/rogue/thief.md
        - Saboteur (HB): class/rogue/saboteur.md
        - Swashbuckler (HB): class/rogue/swashbuckler.md
    - Mage Group:
      - Sorcerer:
        - class/sorcerer/index.md
        - Abberant Sorcery: class/sorcerer/aberrant.md
        - Clockwork Sorcery: class/sorcerer/clockwork.md
        - Draconic Sorcery: class/sorcerer/draconic.md
        - Wild Magic Sorcery: class/sorcerer/wild.md
        - Stone Sorcery (HB): class/sorcerer/stone.md
        - Voidwielder (HB): class/sorcerer/voidwielder.md
      - Warlock:
        - class/warlock/index.md
        - Archfey: class/warlock/archfey.md
        - Celestial: class/warlock/celestial.md
        - Fiend: class/warlock/fiend.md
        - Great Old One: class/warlock/great-old-one.md
      - Wizard:
        - class/wizard/index.md
        - Abjurer: class/wizard/abjurer.md
        - Diviner: class/wizard/diviner.md
        - Evoker: class/wizard/evoker.md
        - Illusionist: class/wizard/illusionist.md
        - Bladesinger (HB): class/wizard/bladesinger.md
        - Chronurgist (HB): class/wizard/chronurgist.md
        - Graviturgist (HB): class/wizard/graviturgist.md
    - Priest Group:
      - Cleric:
        - class/cleric/index.md
        - Life: class/cleric/life.md
        - Light: class/cleric/light.md
        - Trickery: class/cleric/trickery.md
        - War: class/cleric/war.md
        - Destruction (HB): class/cleric/destruction.md
      - Druid:
        - class/druid/index.md
        - Land: class/druid/land.md
        - Moon: class/druid/moon.md
        - Sea: class/druid/sea.md
        - Stars (HB): class/druid/star.md
        - Forged (HB): class/druid/forged.md
      - Paladin:
        - class/paladin/index.md
        - Devotion: class/paladin/devotion.md
        - Glory: class/paladin/glory.md
        - The Ancient: class/paladin/ancient.md
        - Vengeance: class/paladin/vengeance.md
        - Watchers (HB): class/paladin/watchers.md
        - Oathbreaker (HB): class/paladin/oathbreaker.md
    - Warrior Group:
      - Barbarian:  
        - class/barbarian/index.md
        - Berserker: class/barbarian/berserker.md
        - Wild Heart: class/barbarian/wild-heart.md
        - World Tree: class/barbarian/world-tree.md
        - Zealot: class/barbarian/zealot.md
        - Giant (HB): class/barbarian/giant.md
        - Tranquillity (HB): class/barbarian/tranquillity.md
      - Fighter:
        - class/fighter/index.md
        - Battlemaster: class/fighter/battlemaster.md
        - Champion: class/fighter/champion.md
        - Eldritch Knight: class/fighter/eldritch-knight.md
        - Psi Warrior: class/fighter/psi-warrior.md
        - Samurai (HB): class/fighter/samurai.md
        - Witchblade (HB): class/fighter/witchblade.md
      - Monk:
        - class/monk/index.md
        - Mercy: class/monk/mercy.md
        - Shadow: class/monk/shadow.md
        - Hand: class/monk/hand.md
        - Elements: class/monk/element.md
        - Astral Self (HB): class/monk/astral.md
        - Wuxia (HB): class/monk/wuxia.md
  - Spells:
    - Gaining Spells: spells/gaining-spells.md
    - Casting Spells: spells/casting-spells.md
    - Spells Description:
      - 2024 PHB: 
        - Spells (A): spells/description/a.md
        - Spells (B): spells/description/b.md
        - Spells (C): spells/description/c.md
        - Spells (D): spells/description/d.md
        - Spells (E): spells/description/e.md
        - Spells (F): spells/description/f.md
        - Spells (G): spells/description/g.md
        - Spells (H): spells/description/h.md
        - Spells (I): spells/description/i.md
        - Spells (J): spells/description/j.md
        - Spells (K): spells/description/k.md
        - Spells (L): spells/description/l.md
        - Spells (M): spells/description/m.md
        - Spells (N): spells/description/n.md
        - Spells (O): spells/description/o.md
        - Spells (P): spells/description/p.md
        - Spells (R): spells/description/r.md
        - Spells (S): spells/description/s.md
        - Spells (T): spells/description/t.md
        - Spells (U): spells/description/u.md
        - Spells (V): spells/description/v.md
        - Spells (W): spells/description/w.md
        - Spells (Y): spells/description/y.md
        - Spells (Z): spells/description/z.md
      - Crown & Misery: 
        - Spells (C): spells/description/hb/c.md
        - Spells (E): spells/description/hb/e.md
        - Spells (S): spells/description/hb/s.md       
  - Rule Glossary: glossary.md
  - Current Campaign:
    - Player's Gimmick:
      - John K. Godsmith: 
        - campaign/player-chr/john-godsmith/index.md
      - Ydastriel Khaine: 
        - campaign/player-chr/ydastriel-khaine/index.md
      - Eris Decrat: 
        - campaign/player-chr/eris-dekrat/index.md
        - Spell List: campaign/player-chr/eris-dekrat/spell-list.md
# Author
site_author: Eschatologue
site_description: >-
 A wiki made for a personal D&D campaign

# CSS
extra_css:
  - assets/css/extra.css

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - content.tooltips
    - admonition
    - pymdownx.details
    - pymdownx.superfences
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: teal
  font:
    code: Roboto Code
    text: Roboto
  icon: 
    logo: fontawesome/solid/dice-d20
    annotation: material/timeline-question
  favicon: assets/icon.jpg

# Markdown Extentions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
#      permalink: true
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  
# Additional Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/eschatologue"  target="_blank" rel="noopener">Eschatologue</a>